/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ProjectComponent {
        "projectName": string;
    }
    interface ProjectSlider {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLProjectComponentElement extends Components.ProjectComponent, HTMLStencilElement {
    }
    var HTMLProjectComponentElement: {
        prototype: HTMLProjectComponentElement;
        new (): HTMLProjectComponentElement;
    };
    interface HTMLProjectSliderElement extends Components.ProjectSlider, HTMLStencilElement {
    }
    var HTMLProjectSliderElement: {
        prototype: HTMLProjectSliderElement;
        new (): HTMLProjectSliderElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "project-component": HTMLProjectComponentElement;
        "project-slider": HTMLProjectSliderElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ProjectComponent {
        "projectName"?: string;
    }
    interface ProjectSlider {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "project-component": ProjectComponent;
        "project-slider": ProjectSlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "project-component": LocalJSX.ProjectComponent & JSXBase.HTMLAttributes<HTMLProjectComponentElement>;
            "project-slider": LocalJSX.ProjectSlider & JSXBase.HTMLAttributes<HTMLProjectSliderElement>;
        }
    }
}
