/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProjectComponent {
        "isActive": boolean;
        "projectName": string;
        "setActive": (active: boolean) => Promise<void>;
        "setSide": (dir: number) => Promise<void>;
    }
    interface ProjectSlider {
    }
    interface SceneViewer {
    }
}
declare global {
    interface HTMLProjectComponentElement extends Components.ProjectComponent, HTMLStencilElement {
    }
    var HTMLProjectComponentElement: {
        prototype: HTMLProjectComponentElement;
        new (): HTMLProjectComponentElement;
    };
    interface HTMLProjectSliderElement extends Components.ProjectSlider, HTMLStencilElement {
    }
    var HTMLProjectSliderElement: {
        prototype: HTMLProjectSliderElement;
        new (): HTMLProjectSliderElement;
    };
    interface HTMLSceneViewerElement extends Components.SceneViewer, HTMLStencilElement {
    }
    var HTMLSceneViewerElement: {
        prototype: HTMLSceneViewerElement;
        new (): HTMLSceneViewerElement;
    };
    interface HTMLElementTagNameMap {
        "project-component": HTMLProjectComponentElement;
        "project-slider": HTMLProjectSliderElement;
        "scene-viewer": HTMLSceneViewerElement;
    }
}
declare namespace LocalJSX {
    interface ProjectComponent {
        "isActive"?: boolean;
        "projectName"?: string;
    }
    interface ProjectSlider {
    }
    interface SceneViewer {
    }
    interface IntrinsicElements {
        "project-component": ProjectComponent;
        "project-slider": ProjectSlider;
        "scene-viewer": SceneViewer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "project-component": LocalJSX.ProjectComponent & JSXBase.HTMLAttributes<HTMLProjectComponentElement>;
            "project-slider": LocalJSX.ProjectSlider & JSXBase.HTMLAttributes<HTMLProjectSliderElement>;
            "scene-viewer": LocalJSX.SceneViewer & JSXBase.HTMLAttributes<HTMLSceneViewerElement>;
        }
    }
}
